project:
  type: book

book:
  title: "PRACTICALS"
  author: "Michael Bryant"
  date: "2/7/2025"
  chapters:
    - index.qmd
    - PRAC 2.qmd
    - PRAC 3.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

