project:
  type: book

book:
  title: "PRAC1"
  author: "Michael Bryant"
  date: "2/7/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

